<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="JsonProcess" Id="{11c3a8a2-056c-420e-92ea-7ef47e7260b6}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM JsonProcess
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="JsonProcess">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>