<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="JsonProfile" Id="{4a425384-29d1-4a30-9cec-aa8bcc473a61}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM JsonProfile
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="JsonProfile">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>