<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="PresisProcess" Id="{ff4892ec-2976-4f3e-802c-a8e846b23a29}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PresisProcess
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="PresisProcess">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>